'use client';
import { Suspense, useEffect,useRef,useState } from 'react';
import { useSearchParams } from 'next/navigation';
import Shell from '@/components/Shell';
import Icon from '@/components/Icons';
import { Avatar,timeAgo } from '@/components/ui';
import { uploadFromDevice } from '@/lib/client-upload';

function mediaIsVideo(url=''){return /\.(mp4|webm|mov)(\?|$)/i.test(url)}
function MessagesInner(){const sp=useSearchParams();const [convos,setConvos]=useState(null);const [cur,setCur]=useState(sp.get('c')||null);const [thread,setThread]=useState(null);const [txt,setTxt]=useState('');const [search,setSearch]=useState('');const [newU,setNewU]=useState('');const [newMode,setNewMode]=useState(false);const [err,setErr]=useState('');const [uploading,setUploading]=useState(false);const input=useRef(null);const bottom=useRef(null);
const loadConvos=()=>fetch('/api/conversations').then(r=>r.json()).then(d=>setConvos(d.conversations||[])).catch(()=>{});useEffect(()=>{loadConvos();const timer=setInterval(loadConvos,3500);return()=>clearInterval(timer)},[]);useEffect(()=>{if(!cur)return;const load=()=>fetch(`/api/conversations/${cur}/messages`).then(r=>r.json()).then(d=>{if(d.messages){setThread(d);setTimeout(()=>bottom.current?.scrollIntoView({behavior:'smooth'}),40)}});load();const t=setInterval(load,3500);return()=>clearInterval(t)},[cur]);
async function start(e){e.preventDefault();if(!newU.trim())return;setErr('');const r=await fetch('/api/conversations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:newU.trim()})});const d=await r.json();if(!r.ok)return setErr(d.error||'Could not start chat.');setNewU('');setNewMode(false);setCur(d.conversation.id);loadConvos();}
async function send(e,mediaUrl=''){e?.preventDefault();if(!txt.trim()&&!mediaUrl)return;const r=await fetch(`/api/conversations/${cur}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:txt,mediaUrl})});const d=await r.json();if(!r.ok)return setErr(d.error||'Could not send.');setTxt('');setThread(x=>x?{...x,messages:[...x.messages,d.message]}:x);loadConvos();}
async function upload(file){if(!file)return;setUploading(true);try{const url=await uploadFromDevice(file);await send(null,url);}catch(error){setErr(error?.message||'Could not upload.');}finally{setUploading(false);}}
const list=(convos||[]).filter(c=>`${c.peer?.name||''} ${c.peer?.username||''}`.toLowerCase().includes(search.toLowerCase()));return <Shell><section className="messages-head"><h1>Messages</h1><button onClick={()=>setNewMode(!newMode)} aria-label="New message"><Icon name="edit" size={21}/></button></section>{err&&<div className="err">{err}</div>}{newMode&&<form onSubmit={start} className="row" style={{marginBottom:10}}><input value={newU} onChange={e=>setNewU(e.target.value)} placeholder="Enter a username"/><button className="btn sm">Chat</button></form>}<div className="searchbar message-search"><Icon name="search" size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search messages…"/></div><div className="msgwrap"><div className="clist">{convos===null?<div className="mut" style={{padding:15}}>Loading messages…</div>:list.length===0?<div className="mut" style={{padding:15}}>No messages yet.</div>:list.map(c=><button className={'citem '+(cur===c.id?'on':'')} onClick={()=>setCur(c.id)} key={c.id}><Avatar user={c.peer} size={43}/><div style={{minWidth:0,flex:1,textAlign:'left'}}><b>{c.peer?.name||c.peer?.username}</b><div className="preview">{c.last?.mediaUrl?'Sent a photo':c.last?.text||'Start chatting'}</div></div><div className="when">{c.unread>0?<span className="unread-dot">{c.unread}</span>:timeAgo(c.last?.createdAt)}</div></button>)}</div></div>{cur&&thread&&<section className="thread"><header className="thread-head"><button onClick={()=>{setCur(null);setThread(null)}}><Icon name="x"/></button><Avatar user={thread.peer} size={34}/><div><b>{thread.peer?.name||thread.peer?.username}</b><span>{thread.blocked?'Unavailable':'Active now'}</span></div></header><div className="tmsgs">{thread.messages.map(m=><div key={m.id} className={'bubble '+(m.senderId===thread.peer?.id?'them':'me')}>{m.mediaUrl&&(mediaIsVideo(m.mediaUrl)?<video src={m.mediaUrl} controls/>:<img src={m.mediaUrl} alt="Shared media"/>)}{m.text}</div>)}<div ref={bottom}/></div>{thread.blocked?<div className="mut center" style={{padding:14,fontSize:12}}>Messaging is unavailable in this conversation.</div>:<form className="tsend" onSubmit={send}><button type="button" onClick={()=>input.current?.click()} aria-label="Gallery"><Icon name="image" size={21}/></button><input ref={input} hidden type="file" accept="image/*,video/*" onChange={e=>upload(e.target.files?.[0])}/><input value={txt} onChange={e=>setTxt(e.target.value)} placeholder={uploading?'Uploading…':'Message…'} disabled={uploading}/><button className="btn" disabled={uploading}><Icon name="send" size={17}/></button></form>}</section>}</Shell>}

export default function Messages(){return <Suspense fallback={<div className="app-loading"><span>Loading VIRO</span></div>}><MessagesInner/></Suspense>}
